name: PR Build and Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Jest ${{ matrix.jest-version }}
    strategy:
      matrix:
        jest-version: [27, 28]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn install
      - run: yarn add -D jest@${{ matrix.jest-version }} @types/jest@${{ matrix.jest-version }} expect@${{ matrix.jest-version }}
      - name: Test
        run: yarn test
